Feature/check team
SoPra-Team-10/Server pull request #56
Opened 2019-05-09 15:31 UTC by jonas-merkle

@aul12 deine Tests laufen nicht ...

2019-05-09 16:26 UTC, pmo73 approved these changes

2019-05-09 18:31 UTC, Timmifixedit requested changes

2019-05-09 18:31 UTC, Timmifixedit commented on Util/ConfigCheck.cpp
> +                    player->position.x > 7 || player->position == gameModel::Position{7,5} || player->position == gameModel::Position{7,6} || player->position == gameModel::Position{7,7}) {
Holt die Mittelzellen einfach über getCell und dann auf Cell::Centre prüfen

2019-05-09 18:31 UTC, Timmifixedit commented on Util/ConfigCheck.cpp
> +                    player->position.x < 9 || player->position == gameModel::Position{9,5} || player->position == gameModel::Position{9,6} || player->position == gameModel::Position{9,7}) {
siehe oben

2019-05-09 18:42 UTC, Timmifixedit commented
Bitte erst mergen, wenn mein pr (#61 ) gemerged wurde

2019-05-09 19:15 UTC, aul12 requested changes

2019-05-09 19:15 UTC, aul12 commented on Game/Game.cpp
> +                (team->beaters[0]->position == environment->bludgers[0]->position ||
Variablen kosten nix

2019-05-09 19:15 UTC, aul12 commented on Game/conversions.cpp
> +
Die leere Zeile kann weg...

2019-05-09 19:15 UTC, aul12 commented on Game/conversions.cpp
> +
Ebenfalls

2019-05-09 19:15 UTC, aul12 commented on Game/conversions.cpp
> +
Auch

2019-05-09 19:15 UTC, aul12 commented on Game/conversions.cpp
> +    throw std::runtime_error("Fatal error! Enum out of bounds");
Der wird immer ins default kommen....

2019-05-09 19:15 UTC, aul12 commented on Util/ConfigCheck.cpp
> +        int TINDERBLAST = 0;
variablen gehören klein...

2019-05-09 20:12 UTC, Timmifixedit commented on Game/conversions.cpp
> +    throw std::runtime_error("Fatal error! Enum out of bounds");
Wieso?

2019-05-09 20:16 UTC, aul12 commented on Game/conversions.cpp
> +    throw std::runtime_error("Fatal error! Enum out of bounds");
Auch wenn der Wert im enum nicht valide ist fliegt der ins default, das untere throw wird nie erreicht werden

2019-05-10 12:48 UTC, aul12 approved these changes

2019-05-11 14:56 UTC, aul12 commented
@Timmifixedit kannst du das bitte nochmal reviewen?

2019-05-13 11:07 UTC, Timmifixedit approved these changes

2019-05-13 11:08 UTC, merged