Halbwegs fertige Spiellogik
SoPra-Team-10/Server pull request #61
Opened 2019-05-09 18:24 UTC by Timmifixedit

2019-05-09 19:22 UTC, aul12 requested changes
Siehe auch #56

2019-05-09 19:22 UTC, aul12 commented on Game/Game.cpp
> +        timer.pause();
Die debug Ausgaben werden bereits von der Lobby gemacht

2019-05-09 19:22 UTC, aul12 commented on Game/Game.cpp
> +        timer.resume();
Ebenfalls

2019-05-09 20:08 UTC, Timmifixedit commented
@aul12 Ich wollte erst den pr hier mergen und dann nochmal alles beim anderen rein.

2019-05-10 09:19 UTC, aul12 approved these changes

2019-05-10 09:24 UTC, jonas-merkle approved these changes

2019-05-10 09:27 UTC, merged