Life test
SoPra-Team-10/Server pull request #73
Opened 2019-05-21 12:28 UTC by Timmifixedit

2019-05-21 12:37 UTC, aul12 requested changes

2019-05-21 12:37 UTC, aul12 commented on Game/Game.cpp
> +                        log.warn("Invalid entities for blusger shot");
Typo

2019-05-21 12:37 UTC, aul12 commented on Game/Game.cpp
> +                    log.warn("Quffle throw has insufficient information");
Typo

2019-05-21 12:37 UTC, aul12 commented on Game/Game.cpp
> +                        log.debug("Impusle was detected as foul");
Typo

2019-05-21 12:37 UTC, aul12 commented on Game/Game.cpp
> +                            if(!snitchCought){
Typo

2019-05-21 12:37 UTC, aul12 commented on Game/Game.cpp
> +                log.warn("Illegal delta request type");
Kann auch in ein case mit fallthrough

2019-05-21 12:37 UTC, aul12 commented on Game/PhaseManager.cpp
> +#include <utility>
Position

2019-05-22 16:30 UTC, aul12 approved these changes

2019-05-23 09:06 UTC, jonas-merkle approved these changes

2019-05-28 10:16 UTC, jonas-merkle approved these changes

2019-05-28 10:24 UTC, merged